version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"

  app:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8080"
